# Ref: https://github.com/marketplace/actions/hashicorp-setup-terraform
name: GitHub-Actions & Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  aws-bucket-deploy:
    name: aws bucket deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # AWS credentials
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      # IaC Terraform Apply
      ## Setup terraform without specifies the CLI version
      - uses: hashicorp/setup-terraform@v2
      ## Apply terraform (IaC)
      - name: Apply terraform
        run: |
          cd iac
          terraform init
          terraform validate
          terraform fmt
          terraform plan
          terraform apply -auto-approve
          terraform destroy -auto-approve